apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: pd-standard-zonal
provisioner: pd.csi.storage.gke.io
parameters:
 type: pd-standard
 replication-type: none
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: pd-standard-regional
provisioner: pd.csi.storage.gke.io
parameters:
 type: pd-standard
 replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: ssd-zonal
provisioner: pd.csi.storage.gke.io
parameters:
 type: pd-ssd
 replication-type: none
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: ssd-regional
provisioner: pd.csi.storage.gke.io
parameters:
 type: pd-ssd
 replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer

